-- INSERT TO TABLE STUDENTS 

INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Wilona','Dantesia','1988/7/10','13165');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Filia','Rilton','1996/9/05','14500');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Isabeau','Varne','1994/7/27','3500'); 
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Earl','Pryn','1987/6/7','2500');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Lambros','Liaskos','1984/9/24','2500');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Nikos','Alivanoglou','1985/2/26','4500');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Panagiotis','Hliopoulos','1986/08/10','12500');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Maria','Sofogianni','1985/01/03','10230');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Sotiris','Michalos','1994/11/25','7200');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Xristonikos','Hatzidimas','1990/10/28','4350');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Pantelis','Karaiskos','1989/2/10','6950');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Morgen','Basterfield','1995/06/18','8995');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Paul','Atreides','1984/9/24','7850');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Leto','Atreides','1980/05/25','10500');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Duncan','Aidaho','1994/09/10','12630');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Jessica','Gesserit','1982/6/26','6500');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Chani','Fremmen','1993/04/22','4200');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Baron','Harkonnen','1980/12/7','14200');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Frank','Herbert','1990/10/8','7000');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS` VALUES (NULL, 'Robert','Rathall','1989/09/17','16200');

-- INSERT TO TABLE TRAINERS
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS` VALUES (NULL, 'James','Gosling','Java');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS` VALUES (NULL, 'Allan','Larsson','MySQL');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS` VALUES (NULL, 'Gary','Gygax','Python');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS` VALUES (NULL, 'Anders','Hejlsberg','C#');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS` VALUES (NULL, 'Steve','Jobs','iOS');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS` VALUES (NULL, 'Alan','Turing','Computer Science');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS` VALUES (NULL, 'Linus','Torvalds','Linux');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS` VALUES (NULL, 'Marcin','Iwinski','Game Development');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS` VALUES (NULL, 'Paul','Baran','Computer Networks');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS` VALUES (NULL, 'Lawrence','Roberts','Network Development');

-- INSERT TO TABLE COURSES

INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`COURSES` VALUES (NULL, 'Java',' Learn Java ','Full Time', '2020/05/03', '2020/06/12');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`COURSES` VALUES (NULL, 'Python',' Learning Python','Part Time', '2020/01/14', '2021/06/12');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`COURSES` VALUES (NULL, 'C#',' The Art Of Programming','Part Time', '2019/04/10', '2019/11/23');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`COURSES` VALUES (NULL, 'Programming','Algorithms','Full Time', '2020/02/01', '2020/09/12');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`COURSES` VALUES (NULL, 'Network',' Computer Networks ','Part Time', '2020/04/07', '2020/10/23');

-- INSERT TO TABLE ASSIGNMENTS

INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS` VALUES (NULL, 'Java',' Creating an Application ','2020/06/07', NULL);
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS` VALUES (NULL, 'Programming',' Creating A Programm ','2020/07/23', NULL);
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS` VALUES (NULL, 'Network','Network Protocols ','2020/09/24', NULL);
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS` VALUES (NULL, 'Python',' Making a Software','2020/06/10', NULL);
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS` VALUES (NULL, 'C#',' Using C#','2020/10/24', NULL);

-- INSERT TO TABLE STUDENTS_PER_COURSE

INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'1' ,'1');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'2' ,'2');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'3' ,'3');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'4' ,'4');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'5' ,'5');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'1' ,'6');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'2' ,'7');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'3' ,'8');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'4' ,'9');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'5' ,'10');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'1' ,'11');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'2' ,'12');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'3' ,'13');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'4' ,'14');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'5' ,'15');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'1' ,'16');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'2' ,'17');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'3' ,'18');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'4' ,'19');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`STUDENTS_PER_COURSE` VALUES (NULL,'5' ,'20');


-- INSERT TO TABLE TRAINERS_PER_COURSE

INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS_PER_COURSE` VALUES (NULL,'1' ,'1');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS_PER_COURSE` VALUES (NULL,'2' ,'3');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS_PER_COURSE` VALUES (NULL,'4' ,'2');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS_PER_COURSE` VALUES (NULL,'3' ,'4');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS_PER_COURSE` VALUES (NULL,'4' ,'6');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS_PER_COURSE` VALUES (NULL,'5' ,'9');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS_PER_COURSE` VALUES (NULL,'5' ,'10');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS_PER_COURSE` VALUES (NULL,'1' ,'5');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS_PER_COURSE` VALUES (NULL,'2' ,'7');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`TRAINERS_PER_COURSE` VALUES (NULL,'3' ,'8');

-- INSERT TO TABLE ASSIGNMENTS_PER_COURSE

INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE` VALUES (NULL,'1' ,'1');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE` VALUES (NULL,'2' ,'4');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE` VALUES (NULL,'5' ,'3');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE` VALUES (NULL,'4' ,'2');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE` VALUES (NULL,'3' ,'5');





-- INSERT TO TABLE ASSIGNMENTS_PER_COURSE_PER_STUDENT

INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'1' ,'1','1');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'2' ,'4','2');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'3' ,'5','3');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'4' ,'2','4');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'5' ,'3','5');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'1' ,'1','6');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'2' ,'4','7');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'3' ,'5','8');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'4' ,'2','9');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'5' ,'3','10');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'1' ,'1','11');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'2' ,'4','12');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'3' ,'5','13');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'4' ,'2','14');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'5' ,'3','15');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'1' ,'1','16');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'2' ,'4','17');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'3' ,'5','18');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'4' ,'2','19');
INSERT INTO `ASGARD_PRIVATE_SCHOOL`.`ASSIGNMENTS_PER_COURSE_PER_STUDENT` VALUES (NULL,'5' ,'3','20');