-- SELECT ALL STUDENTS
SELECT * FROM STUDENTS;

-- SELECT ALL TRAINERS
SELECT * FROM TRAINERS;

-- SELECT ALL ASSIGNMENTS
SELECT * FROM ASSIGNMENTS;

-- SELECT ALL COURSES
SELECT * FROM COURSES;


-- SELECT STUDENTS PER COURSE
SELECT TITLE AS Course_Title, FIRST_NAME AS Student_First_Name, LAST_NAME AS Student_Last_Name
FROM STUDENTS
JOIN STUDENTS_PER_COURSE ON STUDENTS_PER_COURSE.STUDENT_ID = STUDENTS.ID
JOIN COURSES ON COURSES.ID = STUDENTS_PER_COURSE.COURSE_ID;

-- SELECT TRAINERS PER COURSE
SELECT TITLE AS Course_Title ,FIRST_NAME AS Trainer_First_Name, LAST_NAME AS Trainer_Last_Name
FROM TRAINERS
JOIN TRAINERS_PER_COURSE ON TRAINERS_PER_COURSE.TRAINER_ID = TRAINERS.ID
JOIN COURSES ON COURSES.ID = TRAINERS_PER_COURSE.COURSE_ID;

-- SELECT ASSIGNMENTS PER COURSE
SELECT COURSES.TITLE AS Course_Title ,ASSIGNMENTS.TITLE AS Assignment_Title, ASSIGNMENTS.DESCRIPTION AS Assignemt_Description
FROM ASSIGNMENTS
JOIN ASSIGNMENTS_PER_COURSE ON ASSIGNMENTS_PER_COURSE.ASSIGNMENT_ID = ASSIGNMENTS.ID
JOIN COURSES ON COURSES.ID = ASSIGNMENTS_PER_COURSE.COURSE_ID;

-- SELECT ASSIGNMENTS PER COURSE PER STUDENT
SELECT COURSES.TITLE AS Course_Title ,ASSIGNMENTS.TITLE AS Assignment_Title, ASSIGNMENTS.DESCRIPTION AS Assignemt_Description, STUDENTS.FIRST_NAME AS Student_First_Name, STUDENTS.LAST_NAME AS Students_Last_Name
FROM STUDENTS
JOIN ASSIGNMENTS_PER_COURSE_PER_STUDENT ON ASSIGNMENTS_PER_COURSE_PER_STUDENT.STUDENT_ID = STUDENTS.ID
JOIN COURSES ON COURSES.ID = ASSIGNMENTS_PER_COURSE_PER_STUDENT.COURSE_ID
JOIN ASSIGNMENTS ON ASSIGNMENTS.ID = ASSIGNMENTS_PER_COURSE_PER_STUDENT.ASSIGNMENT_ID;

-- SELECT STUDENTS THAT BELONG TO MORE THAN ONE COURSES

SELECT STUDENTS_PER_COURSE.STUDENT_ID AS Student_ID, STUDENTS.FIRST_NAME AS Student_First_Name, STUDENTS.LAST_NAME AS Student_Last_Name,
COUNT(STUDENTS_PER_COURSE.STUDENT_ID) AS TOTAL_COURSES
FROM STUDENTS, STUDENTS_PER_COURSE
WHERE STUDENTS.ID = STUDENTS_PER_COURSE.STUDENT_ID
GROUP BY STUDENTS_PER_COURSE.STUDENT_ID
HAVING COUNT (STUDENTS_PER_COURSE.STUDENT_ID) > 1
ORDER BY STUDENTS_PER_COURSE.STUDENT_ID;
